//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdl_language.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdl_language.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string AdviceLabel {
            get {
                return ResourceManager.GetString("AdviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importo.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvare le modifiche?.
        /// </summary>
        internal static string askSaveChanges {
            get {
                return ResourceManager.GetString("askSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gli allegati sono troppo grandi, non saranno modificati. Esco comunque?.
        /// </summary>
        internal static string attachmentTooBig {
            get {
                return ResourceManager.GetString("attachmentTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esportazione errata.
        /// </summary>
        internal static string badExport {
            get {
                return ResourceManager.GetString("badExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grassetto.
        /// </summary>
        internal static string bold {
            get {
                return ResourceManager.GetString("bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A causa di un bug di Office, documentato qui: http://support.microsoft.com/kb/320369 è necessario installare Microsoft Office XP Multilingual User Interface Pack..
        /// </summary>
        internal static string bugOfficeXp {
            get {
                return ResourceManager.GetString("bugOfficeXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La chiusura del form è temporaneamente inibita, attendere..
        /// </summary>
        internal static string cantCloseWait {
            get {
                return ResourceManager.GetString("cantCloseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare l&apos;oggetto..
        /// </summary>
        internal static string cantDeleteObject {
            get {
                return ResourceManager.GetString("cantDeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per chiudere una maschera è necessario prima chiudere le maschere da essa dipendenti..
        /// </summary>
        internal static string childFormStillOpened {
            get {
                return ResourceManager.GetString("childFormStillOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il comando {cmd} ha invalidato la transazione.
        /// </summary>
        internal static string cmdInvalidatedTransaction {
            get {
                return ResourceManager.GetString("cmdInvalidatedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; necessario selezionare una colonna.
        /// </summary>
        internal static string colRequired {
            get {
                return ResourceManager.GetString("colRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome colonna.
        /// </summary>
        internal static string columnName {
            get {
                return ResourceManager.GetString("columnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La condizione di ricerca impostata era: &apos;{filter}&apos;..
        /// </summary>
        internal static string conditionSetWas {
            get {
                return ResourceManager.GetString("conditionSetWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare l&apos;elenco {listType}.
        /// </summary>
        internal static string confirmDeleteListType {
            get {
                return ResourceManager.GetString("confirmDeleteListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler cancellare?.
        /// </summary>
        internal static string confirmDeleting {
            get {
                return ResourceManager.GetString("confirmDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        internal static string confirmTitle {
            get {
                return ResourceManager.GetString("confirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sono riuscito a collegare la riga alla tabella {tableName} nel metadato {name}.
        /// </summary>
        internal static string couldNotLinkTable {
            get {
                return ResourceManager.GetString("couldNotLinkTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La voce selezionata non poteva essere scelta..
        /// </summary>
        internal static string couldNotSelectRow {
            get {
                return ResourceManager.GetString("couldNotSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creato il {data}.
        /// </summary>
        internal static string createdAt {
            get {
                return ResourceManager.GetString("createdAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creato da {user}.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creazione/Ultima Modifica.
        /// </summary>
        internal static string CreateLastMod {
            get {
                return ResourceManager.GetString("CreateLastMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea ticket.
        /// </summary>
        internal static string CreateTicketLabel {
            get {
                return ResourceManager.GetString("CreateTicketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizionario dati.
        /// </summary>
        internal static string DataDictionary {
            get {
                return ResourceManager.GetString("DataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foglio Dati.
        /// </summary>
        internal static string dataFolder {
            get {
                return ResourceManager.GetString("dataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La connessione al db è stata interrotta. E&apos; necessario disconnettersi, ripristinare la rete e riconnettersi al db..
        /// </summary>
        internal static string dbConnectionInterrupted {
            get {
                return ResourceManager.GetString("dbConnectionInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome campo su DB.
        /// </summary>
        internal static string dbFieldName {
            get {
                return ResourceManager.GetString("dbFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabella sul db.
        /// </summary>
        internal static string dbTableName {
            get {
                return ResourceManager.GetString("dbTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina/Annulla.
        /// </summary>
        internal static string DeleteCancelLabel {
            get {
                return ResourceManager.GetString("DeleteCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancello l&apos;oggetto {name} dalla tabella {tableName}.
        /// </summary>
        internal static string deleteFromTable {
            get {
                return ResourceManager.GetString("deleteFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string DeleteLable {
            get {
                return ResourceManager.GetString("DeleteLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancello la riga selezionata dalla tabella {name}({tableName}).
        /// </summary>
        internal static string deleteSelectedRowFromTable {
            get {
                return ResourceManager.GetString("deleteSelectedRowFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descrizione.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effettua Ricerca.
        /// </summary>
        internal static string DoSearchLabel {
            get {
                return ResourceManager.GetString("DoSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO_SYSCMD: Error running {cmd} Result got: {res}.
        /// </summary>
        internal static string doSysCmdError {
            get {
                return ResourceManager.GetString("doSysCmdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correggi.
        /// </summary>
        internal static string EditLable {
            get {
                return ResourceManager.GetString("EditLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esportazione vuota.
        /// </summary>
        internal static string emptyExport {
            get {
                return ResourceManager.GetString("emptyExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (vuoto).
        /// </summary>
        internal static string EmptyWithinPar {
            get {
                return ResourceManager.GetString("EmptyWithinPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore aprendo la connessione nel salvataggio.
        /// </summary>
        internal static string errOpeningDuringSave {
            get {
                return ResourceManager.GetString("errOpeningDuringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare l&apos;elenco  {listType}.
        /// </summary>
        internal static string errorDeletingListType {
            get {
                return ResourceManager.GetString("errorDeletingListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un determinato campo non può essere vuoto..
        /// </summary>
        internal static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un campo chiave non può essere vuoto o duplicato..
        /// </summary>
        internal static string ErrorEmptyKey {
            get {
                return ResourceManager.GetString("ErrorEmptyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;esportazione in Excel. Riprovare e se l&apos;errore persiste contattare l&apos;assistenza..
        /// </summary>
        internal static string errorExportingExcel {
            get {
                return ResourceManager.GetString("errorExportingExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel caricamento del metadato {unaliased}. E&apos; necessario riavviare il programma..
        /// </summary>
        internal static string errorLoadingMeta {
            get {
                return ResourceManager.GetString("errorLoadingMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore aprendo la connessione.
        /// </summary>
        internal static string errorOpeningConnection {
            get {
                return ResourceManager.GetString("errorOpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;esecuzione del comando {command}.
        /// </summary>
        internal static string errorRunningCommand {
            get {
                return ResourceManager.GetString("errorRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore eseguendo il comando {cmd}
        ///E&apos; necessario chiudere la maschera..
        /// </summary>
        internal static string errorRunningCommandCloseWindow {
            get {
                return ResourceManager.GetString("errorRunningCommandCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nella selezione della riga.
        /// </summary>
        internal static string errorSelectingRow {
            get {
                return ResourceManager.GetString("errorSelectingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nella visualizzazione del form.
        /// </summary>
        internal static string errorShowingForm {
            get {
                return ResourceManager.GetString("errorShowingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo carattere.
        /// </summary>
        internal static string fontName {
            get {
                return ResourceManager.GetString("fontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensione carattere.
        /// </summary>
        internal static string fontSize {
            get {
                return ResourceManager.GetString("fontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare le condizioni.
        /// </summary>
        internal static string impossibleToDeleteConditions {
            get {
                return ResourceManager.GetString("impossibleToDeleteConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile salvare la condizione.
        /// </summary>
        internal static string impossibleToSaveCondition {
            get {
                return ResourceManager.GetString("impossibleToSaveCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni sull&apos;oggetto.
        /// </summary>
        internal static string InfoAboutObject {
            get {
                return ResourceManager.GetString("InfoAboutObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annullo l&apos;inserimento dell&apos;oggetto {name} nella tabella {tableName}.
        /// </summary>
        internal static string insertCancelOnTable {
            get {
                return ResourceManager.GetString("insertCancelOnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; stato premuto il tasto inserisci copia. Si desidera davvero creare una copia dei dati già salvati?.
        /// </summary>
        internal static string InsertCopyConfirm {
            get {
                return ResourceManager.GetString("InsertCopyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci copia.
        /// </summary>
        internal static string InsertCopyLabel {
            get {
                return ResourceManager.GetString("InsertCopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci.
        /// </summary>
        internal static string InsertLabel {
            get {
                return ResourceManager.GetString("InsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tabella {tableName} contiene dati non validi. Contattare il servizio di assistenza..
        /// </summary>
        internal static string invalidDataOnTable {
            get {
                return ResourceManager.GetString("invalidDataOnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data non valida.
        /// </summary>
        internal static string invalidDate {
            get {
                return ResourceManager.GetString("invalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsivo.
        /// </summary>
        internal static string italic {
            get {
                return ResourceManager.GetString("italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione colonna.
        /// </summary>
        internal static string listColPos {
            get {
                return ResourceManager.GetString("listColPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Elenco: &apos;{listingType}&apos;..
        /// </summary>
        internal static string listNameIs {
            get {
                return ResourceManager.GetString("listNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco {name}.
        /// </summary>
        internal static string ListOfName {
            get {
                return ResourceManager.GetString("ListOfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificato il {data}.
        /// </summary>
        internal static string modifiedAt {
            get {
                return ResourceManager.GetString("modifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificato da {user}.
        /// </summary>
        internal static string modifiedBy {
            get {
                return ResourceManager.GetString("modifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: C&apos;è più di una riga nella tabella {table}.
        /// </summary>
        internal static string moreThanOneRowInTable {
            get {
                return ResourceManager.GetString("moreThanOneRowInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna condizione è stata usata..
        /// </summary>
        internal static string noConditionUsed {
            get {
                return ResourceManager.GetString("noConditionUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun elemento trovato..
        /// </summary>
        internal static string NoElementFound {
            get {
                return ResourceManager.GetString("NoElementFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun oggetto trovato.
        /// </summary>
        internal static string noObjectFound {
            get {
                return ResourceManager.GetString("noObjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna riga trovata..
        /// </summary>
        internal static string NoRowFound {
            get {
                return ResourceManager.GetString("NoRowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nella tabella &apos;{table}&apos; non è stata trovata alcuna riga..
        /// </summary>
        internal static string noRowFoundInTable {
            get {
                return ResourceManager.GetString("noRowFoundInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appunti.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transazione corrente non è più valida.
        /// </summary>
        internal static string noValidTransaction {
            get {
                return ResourceManager.GetString("noValidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri documento collegato.
        /// </summary>
        internal static string OpenRelatedDocument {
            get {
                return ResourceManager.GetString("OpenRelatedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; necessario selezionare un operatore.
        /// </summary>
        internal static string operatorRequired {
            get {
                return ResourceManager.GetString("operatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale Complessivo.
        /// </summary>
        internal static string overallTotal {
            get {
                return ResourceManager.GetString("overallTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; stata inserita una riga con la stessa chiave primaria di un altra esistente.  E&apos; necessario modificare i dati immessi per salvarli..
        /// </summary>
        internal static string primaryKeyConflict {
            get {
                return ResourceManager.GetString("primaryKeyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readObjectArray: Error running {query}.
        /// </summary>
        internal static string readObjArrayError {
            get {
                return ResourceManager.GetString("readObjArrayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna.
        /// </summary>
        internal static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to risultato.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riga richiesta non trovata.
        /// </summary>
        internal static string rowNotFound {
            get {
                return ResourceManager.GetString("rowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvataggio.
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ricerca).
        /// </summary>
        internal static string SearchWithinPar {
            get {
                return ResourceManager.GetString("SearchWithinPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La riga selezionata non è più presente nel db..
        /// </summary>
        internal static string selectedRowNotPresent {
            get {
                return ResourceManager.GetString("selectedRowNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il file da creare.
        /// </summary>
        internal static string selectFile {
            get {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona.
        /// </summary>
        internal static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposta Ricerca.
        /// </summary>
        internal static string SetSearchLabel {
            get {
                return ResourceManager.GetString("SetSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendere l&apos;apertura del form per chiuderlo!.
        /// </summary>
        internal static string stillNotOpenedForm {
            get {
                return ResourceManager.GetString("stillNotOpenedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo troppo lungo.
        /// </summary>
        internal static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabella:{searchTable}
        ///Filtro applicato:{checkfilter}.
        /// </summary>
        internal static string TableFilterApplied {
            get {
                return ResourceManager.GetString("TableFilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabella:{middle} presente in memoria..
        /// </summary>
        internal static string TableMiddleInMemory {
            get {
                return ResourceManager.GetString("TableMiddleInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolo.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sottolineato.
        /// </summary>
        internal static string underline {
            get {
                return ResourceManager.GetString("underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ci sono modifiche ai dati non salvate. Si desidera perdere le modifiche?.
        /// </summary>
        internal static string unsavedDataWarn {
            get {
                return ResourceManager.GetString("unsavedDataWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; necessario inserire un valore.
        /// </summary>
        internal static string valueRequired {
            get {
                return ResourceManager.GetString("valueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibile.
        /// </summary>
        internal static string visible {
            get {
                return ResourceManager.GetString("visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendere la fine dell&apos;esecuzione del comando.
        /// </summary>
        internal static string waitForCommandCompletion {
            get {
                return ResourceManager.GetString("waitForCommandCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendere il completamento dell&apos;operazione per chiudere il form..
        /// </summary>
        internal static string waitForOperationEnd {
            get {
                return ResourceManager.GetString("waitForOperationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        internal static string WarningLabel {
            get {
                return ResourceManager.GetString("WarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larghezza.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per poter procedere è necessario CHIUDERE la finestra con cui si stava lavorando e ripetere l&apos;operazione.
        ///E&apos; consigliabile ad ogni modo chiamare il servizio assistenza lasciando aperta questa schermata..
        /// </summary>
        internal static string windowMustBeClosed {
            get {
                return ResourceManager.GetString("windowMustBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati errati.
        /// </summary>
        internal static string wrongData {
            get {
                return ResourceManager.GetString("wrongData", resourceCulture);
            }
        }
    }
}
