using System;
using System.Data;
#pragma warning disable IDE1006 // Naming Styles

namespace mdl {

	/// <summary>
	/// Summary description for creaDatiSistema.
	/// </summary>
	public class creaDatiSistema {

		/// <summary>
		/// Crea in ds.columntypes le righe relative a customobject
		/// </summary>
		/// <param name="ds"></param>
		public static void Settacustomobject(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customobject";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customobject";
			r2["field"]="description";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customobject";
			r2["field"]="isreal";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customobject";
			r2["field"]="realtable";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customobject";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customobject";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}


        /// <summary>
                               /// Crea in ds.columntypes le righe relative a customview
                               /// </summary>
                               /// <param name="ds"></param>
        public static void Settacustomview(dbstructure ds) {
            var r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="viewname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="35";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(35)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="bottommargin";
			r2["iskey"]="N";
			r2["sqltype"]="float";
			r2["col_len"]="8";
			r2["systemtype"]="System.Double";
			r2["sqldeclaration"]="float";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="colheading";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="1";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="fittopage";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="footer";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="gridlines";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="hcenter";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="header";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="hpages";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="isreal";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="1";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="issystem";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="N";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="landscape";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="leftmargin";
			r2["iskey"]="N";
			r2["sqltype"]="float";
			r2["col_len"]="8";
			r2["systemtype"]="System.Double";
			r2["sqldeclaration"]="float";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="lefttoright";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="rightmargin";
			r2["iskey"]="N";
			r2["sqltype"]="float";
			r2["col_len"]="8";
			r2["systemtype"]="System.Double";
			r2["sqldeclaration"]="float";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="rowheading";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="scale";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="staticfilter";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="1000";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(1000)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="topmargin";
			r2["iskey"]="N";
			r2["sqltype"]="float";
			r2["col_len"]="8";
			r2["systemtype"]="System.Double";
			r2["sqldeclaration"]="float";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="vcenter";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customview";
			r2["field"]="vpages";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a customviewcolumn
        /// </summary>
        /// <param name="ds"></param>
	    public static void Settacustomviewcolumn(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="colnumber";
			r2["iskey"]="S";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="viewname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="35";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(35)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="bold";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="colname";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="color";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="colwidth";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="expression";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="100";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(100)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="fontname";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="fontsize";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="format";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="heading";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="isreal";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="1";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="italic";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="listcolpos";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="strikeout";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="systemtype";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="underline";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewcolumn";
			r2["field"]="visible";
			r2["iskey"]="N";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="S";
			r2["defaultvalue"]="1";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a customorderby
        /// </summary>
        /// <param name="ds"></param>
		public static void Settacustomvieworderby(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="periodnumber";
			r2["iskey"]="S";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="viewname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="35";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(35)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="columnname";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="direction";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customvieworderby";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a customoviewwhere
        /// </summary>
        /// <param name="ds"></param>
		public static void Settacustomviewwhere(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="periodnumber";
			r2["iskey"]="S";
			r2["sqltype"]="smallint";
			r2["col_len"]="2";
			r2["systemtype"]="System.Int16";
			r2["sqldeclaration"]="smallint";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="viewname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="35";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(35)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="columnname";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="connector";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="1";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="operator";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="runtime";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="0";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customviewwhere";
			r2["field"]="value";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="255";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(255)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a customtablestructure
        /// </summary>
        /// <param name="ds"></param>
		public static void Settacustomtablestructure(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="colname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="autoincrement";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="step";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="prefixfieldname";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="middleconst";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="length";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="N";
			r2["defaultvalue"]="7";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="linear";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="selector";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customtablestructure";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a customredirect
        /// </summary>
        /// <param name="ds"></param>
		public static void Settacustomredirect(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="viewname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="35";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(35)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="objecttarget";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customredirect";
			r2["field"]="viewtarget";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="35";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(35)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a customedit
        /// </summary>
        /// <param name="ds"></param>
		public static void Settacustomedit(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="edittype";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="50";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(50)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="caption";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="defaultlisttype";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="dllname";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="list";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="N";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="searchenabled";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="N";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="startempty";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="N";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="customedit";
			r2["field"]="tree";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="S";
			r2["defaultvalue"]="N";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a viewcolumn
        /// </summary>
        /// <param name="ds"></param>
		public static void Settaviewcolumn(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="viewcolumn";
			r2["field"]="colname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="viewcolumn";
			r2["field"]="objectname";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="viewcolumn";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="viewcolumn";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="viewcolumn";
			r2["field"]="realcolumn";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="viewcolumn";
			r2["field"]="realtable";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

        /// <summary>
        /// Crea in ds.columntypes le righe relative a columntypes
        /// </summary>
        /// <param name="ds"></param>
		public static void Settacolumntypes(dbstructure ds){
			var r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="tablename";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="field";
			r2["iskey"]="S";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="iskey";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="sqltype";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="60";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(60)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="col_len";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="col_precision";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="col_scale";
			r2["iskey"]="N";
			r2["sqltype"]="int";
			r2["col_len"]="4";
			r2["systemtype"]="System.Int32";
			r2["sqldeclaration"]="int";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="systemtype";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="sqldeclaration";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="allownull";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="defaultvalue";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="format";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="80";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(80)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="denynull";
			r2["iskey"]="N";
			r2["sqltype"]="char";
			r2["col_len"]="1";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="char(1)";
			r2["allownull"]="N";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="S";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="lastmodtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="lastmoduser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="createuser";
			r2["iskey"]="N";
			r2["sqltype"]="varchar";
			r2["col_len"]="30";
			r2["systemtype"]="System.String";
			r2["sqldeclaration"]="varchar(30)";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
			r2= ds.columntypes.NewRow();
			r2["tablename"]="columntypes";
			r2["field"]="createtimestamp";
			r2["iskey"]="N";
			r2["sqltype"]="datetime";
			r2["col_len"]="8";
			r2["systemtype"]="System.DateTime";
			r2["sqldeclaration"]="datetime";
			r2["allownull"]="S";
			r2["defaultvalue"]="";
			r2["format"]="";
			r2["denynull"]="N";
			ds.columntypes.Rows.Add(r2);
			r2.AcceptChanges();
		}

	}
	
	
}
